#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#
# Modified by Mingfei Gao
# 2016.06.17
#

obj-y	:= smdk2440.o
obj-y	+= lowlevel_init.o
obj-y   += download.o
